### ISSUE TITLE
Cannot install (macOS)

### ISSUE THREAD

**Issue by kylewhirl** [justjam2013/homebridge-virtual-accessories#31]
**Describe The Bug:**

The plugin does not install on macOS
**To Reproduce:**

Install plugin from Homebridge ui 
**Expected behavior:**

**Logs:**

```
CMD: npm install -g homebridge-virtual-accessories@1.0.4
[?25l
[..................] | idealTree:lib: sill idealTree
[..................] | idealTree:lib: sill idealTree
[..................] | idealTree:lib: sill idealTree
[..................] | idealTree:lib: sill idealTree
[..................] | idealTree:lib: sill idealTree
[..................] | idealTree:lib: sill idealTree
[..................] / idealTree:lib: sill idealTree
[..................] / idealTree:lib: sill idealTree
[..................] - idealTree:lib: sill idealTree
[..................] \ idealTree:lib: sill idealTree
[..................] | idealTree:lib: sill idealTree
[..................] / idealTree:lib: sill idealTree
[..................] / idealTree:lib: sill idealTree
[..................] / idealTree:lib: sill idealTree
[..................] / idealTree:lib: sill idealTree
[#########.........] / idealTree:lib: timing idealTr
[#########.........] / idealTree:lib: timing idealTr
[#########.........] \ idealTree:lib: timing idealTr
[#########.........] \ idealTree:lib: timing idealTr
[#########.........] - idealTree:lib: timing idealTr
[#########.........] / reify:@js-joda/core: timing r
[#########.........] / reify:@js-joda/core: timing r
[##########........] | reify:net-ping: http fetch GE
[##############....] / reify:luxon: timing reifyNode
[##############....] / reify:luxon: timing reifyNode
[################..] | reify:cron: http fetch GET 20
[#################.] \ reify:@js-joda/core: timing r

> raw-socket@1.8.1 install
> node-gyp rebuild
[##################] / reify:@js-joda/timezone: http
[##################] / reify:@js-joda/timezone: http
[##################] / reify:@js-joda/timezone: http
[##################] / reify:@js-joda/timezone: http
[##################] / reify:@js-joda/timezone: http
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
    import gyp  # noqa: E402
    ^^^^^^^^^^
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
    import gyp.input
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
    from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'
gyp
ERR!
configure error
gyp
ERR!
 stack
 Error: `gyp` failed with exit code: 1
gyp
ERR!
 stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:325:16)
gyp
ERR! stack
     at ChildProcess.emit (node:events:514:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR!
System Darwin 24.1.0
gyp
 ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp
 ERR! cwd /usr/local/lib/node_modules/homebridge-virtual-accessories/node_modules/raw-socket
gyp
ERR! node -v v20.9.0
gyp
ERR! node-gyp -v v9.4.0
gyp
ERR! not ok
[##################] - reify:@js-joda/timezone: http

[?25h
npm
 ERR! code 1
npm ERR!
path /usr/local/lib/node_modules/homebridge-virtual-accessories/node_modules/raw-socket
npm ERR!
 command failed
npm ERR!
 command sh -c node-gyp rebuild.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.0.4
* **Homebridge Version**:  1.8.5
* **Node.js Version**:  20.9.0
* **NPM Version**: 
* **Operating System**:  macOS m4 chip

**Comment by justjam2013** [comment]
Can you provide your version of Homebridge, Homebridge UI, and Node.js?

**Note:** At the moment there is an ongoing issue wth M chip/Arm based Macs and certain versions of HB & Node, which is affecting multiple plugins.

**Comment by kylewhirl** [comment]
Homebridge ui version is 4.63.0 and I edited my issue to include the other info

**Comment by justjam2013** [comment]
I just did a search, as your Homebridge and Homebridge UI versions are the same as mine. I am on Node v22, but Node.js v20 is still supported.

I found this article relating to `node-gyp` failing on M1/M2 chip Macs: [Setting up M1/M2 Mac for using package node-gyp](https://dev.to/steckdev/setting-up-m1m2-mac-for-using-package-node-gyp-1d9e)
The important part is Step 1, installing Xcode Command Line Tools: `xcode-select --install`. You should be able to install the CLT without installing all of Xcode.
I have the CLT installed on my Mac for development purposes, so I didn't run into this problem.

I will have to update the README.

**Comment by kylewhirl** [comment]
I’ve had Xcode command line tools installed alreadyOn Nov 22, 2024, at 12:43 PM, Just Jam ***@***.***> wrote:﻿
I just did a search, as your Homebridge and Homebridge UI versions are the same as mine. I am on Node v22, but Node.js v20 is still supported.
I found this article relating to node-gyp failing on M1/M2 chip Macs: Setting up M1/M2 Mac for using package node-gyp
The important part is Step 1, installing Xcode Command Line Tools: xcode-select --install. You should be able to install the CLT without installing all of Xcode.
I have the CLT installed on my Mac for development purposes, so I didn't run into this problem.
I will have to update the README.

**Comment by justjam2013** [comment]
Looks like this has been an issue with Macs going back years :/

Here are a number of suggestions to try: [trying to 'npm install', getting node-gyp rebuild errors](https://github.com/nodejs/node-gyp/issues/809)
