### ISSUE TITLE
Won’t work with homebridge update

### ISSUE THREAD

**Issue by dvr007** [justjam2013/homebridge-virtual-accessories#66]
**Describe The Bug:**
‘Devices’ no response, in home. Non of them.

**To Reproduce:**
Do an update. Of the plugin, homebridge or homebridge-ui

**Expected behavior:**
‘Devices’ to be avilebele 

**Logs:**

```
USER: xxxxxxxxxx
DIR: /var/lib/homebridge
CMD: npm install --save homebridge-virtual-accessories@1.2.3
npm error Class extends value undefined is not a constructor or null
npm error A complete log of this run can be found in: /home/xxxxxxxxxx/.npm/_logs/2024-12-21T15_31_55_259Z-debug-0.log


Error: Operation failed with code 1.

You can download this log file for future reference.

See https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting for help.
———————

/home/xxxxxxxxxx/.npm/_logs/2024-12-21T15_31_55_259Z-debug-0.log:

0 verbose cli /opt/homebridge/bin/node /opt/homebridge/bin/npm
1 info using npm@10.9.0
2 info using node@v22.12.0
3 silly config load:file:/opt/homebridge/lib/node_modules/npm/npmrc
4 warn config global-style This option has been deprecated in favor of `--install-strategy=shallow`
5 silly config load:file:/var/lib/homebridge/.npmrc
6 warn config global-style This option has been deprecated in favor of `--install-strategy=shallow`
7 silly config load:file:/home/eddy/.npmrc
8 silly config load:file:/opt/homebridge/etc/npmrc
9 verbose title npm install homebridge-virtual-accessories@1.2.3
10 verbose argv "install" "--save" "homebridge-virtual-accessories@1.2.3"
11 verbose logfile logs-max:10 dir:/home/eddy/.npm/_logs/2024-12-21T15_31_55_259Z-
12 verbose logfile /home/eddy/.npm/_logs/2024-12-21T15_31_55_259Z-debug-0.log
13 silly logfile start cleaning logs, removing 2 files
14 verbose stack TypeError: Class extends value undefined is not a constructor or null
14 verbose stack     at Object.<anonymous> (/opt/homebridge/lib/node_modules/npm/node_modules/minipass-collect/index.js:4:23)
14 verbose stack     at Module._compile (node:internal/modules/cjs/loader:1565:14)
14 verbose stack     at Object..js (node:internal/modules/cjs/loader:1708:10)
14 verbose stack     at Module.load (node:internal/modules/cjs/loader:1318:32)
14 verbose stack     at Function._load (node:internal/modules/cjs/loader:1128:12)
14 verbose stack     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
14 verbose stack     at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
14 verbose stack     at Module.require (node:internal/modules/cjs/loader:1340:12)
14 verbose stack     at require (node:internal/modules/helpers:138:16)
14 verbose stack     at Object.<anonymous> (/opt/homebridge/lib/node_modules/npm/node_modules/cacache/lib/get.js:3:17)
15 error Class extends value undefined is not a constructor or null
16 verbose cwd /var/lib/homebridge
17 verbose os Linux 6.6.62+rpt-rpi-v8
18 verbose node v22.12.0
19 verbose npm  v10.9.0
20 verbose exit 1
21 verbose code 1
22 error A complete log of this run can be found in: /home/eddy/.npm/_logs/2024-12-21T15_31_55_259Z-debug-0.log

```

**Plugin Config:**

```

```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.2.x
* **Homebridge Version**: 1.8.5  
* **Node.js Version**: v22.12.0
* **NPM Version**: 10.9.0
* **Operating System**: *** Homebridge Raspbian "homebridge/homebridge-raspbian-image-1.2.2-(64bit)" - Raspberry Pi 4 Model B Rev 1.5 ***

**Comment by dvr007** [comment]
Going back to node.js version 20.10, makes it working again. But that’s not a good solution.

**Comment by justjam2013** [comment]
This appears to be an issue with npm. Please look at the following posts to fix this:

- https://github.com/nodejs/node/issues/42413
- https://stackoverflow.com/questions/78068624/getting-this-error-after-having-windows-reinstalled-on-device-typeerror-class

The main suggestion appears to be to remove `node modules` and reinstall:
```
rm -rf node_modules
npm install
```

I have checked both my Homebridge instances by successfully downgrading and upgrading versions of Homebridge UI and homebridge-virtual-accessories:

**Plugin Version:** 1.2.3
**Homebridge Version:** 1.8.5
**Homebridge UI Version:** 4.65.2
**Node.js Version:** 20.18.0
**NPM Version:** 10.9.0
**Operating System:** Docker image on Raspberry Pi 4 Model B

**Plugin Version:** 1.2.3
**Homebridge Version:** 1.8.5
**Homebridge UI Version:** 5.0.0-beta.22
**Node.js Version:** 22.12.0
**NPM Version:** 10.9.0
**Operating System:** macOS Sonoma

**Comment by justjam2013** [comment]
Update: Updated to latest version and requires rebuild of plugin with latest Node package

**Comment by justjam2013** [comment]
I just upgraded my Raspberry Pi instance to the latest Docker image, using Node 22.x and Homebridge failed to start. Going from Node.js 20.x to Node.js 22.x, I had to reinstall the Node.js native module `raw-socket`.

Immediately after doing the manual update of Node.js run the following commands:
```
npm uninstall raw-socket
npm install raw-socket
```

My Mac instance of Homebridge was fine because the plugin was originally installed on Node.js. It wasn't an upgrade.
